version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - x:size/tiny

  # Enable updates to the dependencies of our Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
