[canonical-tests]

# Real part of a purely real number
"9f98e133-eb7f-45b0-9676-cce001cd6f7a" = true

# Real part of a purely imaginary number
"07988e20-f287-4bb7-90cf-b32c4bffe0f3" = true

# Real part of a number with real and imaginary part
"4a370e86-939e-43de-a895-a00ca32da60a" = true

# Imaginary part of a purely real number
"9b3fddef-4c12-4a99-b8f8-e3a42c7ccef6" = true

# Imaginary part of a purely imaginary number
"a8dafedd-535a-4ed3-8a39-fda103a2b01e" = true

# Imaginary part of a number with real and imaginary part
"0f998f19-69ee-4c64-80ef-01b086feab80" = true

# Imaginary unit
"a39b7fd6-6527-492f-8c34-609d2c913879" = true

# Add purely real numbers
"9a2c8de9-f068-4f6f-b41c-82232cc6c33e" = true

# Add purely imaginary numbers
"657c55e1-b14b-4ba7-bd5c-19db22b7d659" = true

# Add numbers with real and imaginary part
"4e1395f5-572b-4ce8-bfa9-9a63056888da" = true

# Subtract purely real numbers
"1155dc45-e4f7-44b8-af34-a91aa431475d" = true

# Subtract purely imaginary numbers
"f95e9da8-acd5-4da4-ac7c-c861b02f774b" = true

# Subtract numbers with real and imaginary part
"f876feb1-f9d1-4d34-b067-b599a8746400" = true

# Multiply purely real numbers
"8a0366c0-9e16-431f-9fd7-40ac46ff4ec4" = true

# Multiply purely imaginary numbers
"e560ed2b-0b80-4b4f-90f2-63cefc911aaf" = true

# Multiply numbers with real and imaginary part
"4d1d10f0-f8d4-48a0-b1d0-f284ada567e6" = true

# Divide purely real numbers
"b0571ddb-9045-412b-9c15-cd1d816d36c1" = true

# Divide purely imaginary numbers
"5bb4c7e4-9934-4237-93cc-5780764fdbdd" = true

# Divide numbers with real and imaginary part
"c4e7fef5-64ac-4537-91c2-c6529707701f" = true

# Absolute value of a positive purely real number
"c56a7332-aad2-4437-83a0-b3580ecee843" = true

# Absolute value of a negative purely real number
"cf88d7d3-ee74-4f4e-8a88-a1b0090ecb0c" = true

# Absolute value of a purely imaginary number with positive imaginary part
"bbe26568-86c1-4bb4-ba7a-da5697e2b994" = true

# Absolute value of a purely imaginary number with negative imaginary part
"3b48233d-468e-4276-9f59-70f4ca1f26f3" = true

# Absolute value of a number with real and imaginary part
"fe400a9f-aa22-4b49-af92-51e0f5a2a6d3" = true

# Conjugate a purely real number
"fb2d0792-e55a-4484-9443-df1eddfc84a2" = true

# Conjugate a purely imaginary number
"e37fe7ac-a968-4694-a460-66cb605f8691" = true

# Conjugate a number with real and imaginary part
"f7704498-d0be-4192-aaf5-a1f3a7f43e68" = true

# Euler's identity/formula
"6d96d4c6-2edb-445b-94a2-7de6d4caaf60" = true

# Exponential of 0
"2d2c05a0-4038-4427-a24d-72f6624aa45f" = true

# Exponential of a purely real number
"ed87f1bd-b187-45d6-8ece-7e331232c809" = true

# Exponential of a number with real and imaginary part
"08eedacc-5a95-44fc-8789-1547b27a8702" = true
