name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: exercises

jobs:
  build:
    name: Check if tests compile cleanly with starter sources
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Set up JDK 1.17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          java-version: 17
          distribution: "temurin"
      - name: Check if tests compile cleanly with starter sources
        run: ./gradlew compileStarterTestJava --continue
